name: ml_pycaret23
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.3.5
  - scikit-learn=0.23.2
  - numpy=1.20.3
  - scipy=1.6.3
  - matplotlib=3.5.3
  - seaborn=0.11.2
  - jupyterlab
  - pip
  - pip:
      - pycaret==2.3.10
      - ydata-profiling==4.1.2
      - lightgbm==3.3.5
      - xgboost==1.5.2
      - catboost==1.2